<?php
/**
 * @file
 * Islandora Bioinformatics Fraction Module
 * 
 * @author Nolan Phillips ncphillips@upei.ca
 * @author Brent Mitton bmitton@upei.ca
 * @author Natasha Squires nbsquires@upei.ca
 * @author Quintin Dawson qdawson@upei.ca
 */

/**
 * Menu items for the assay solpack.
 * @todo
 *  refactor
 * @return array
 */
function islandora_lab_object_fraction_menu(){
  return array(
    'assay/assays' => array(
      'title' => "Autocomplete Assays",
      'page callback' => "_assay_autocomplete",
      'access arguments' => TRUE,
      'type' => MENU_CALLBACK,
    ),

  );
}


/**
 * @param $object
 * @return bool
 * @todo assay_cmodel to fraction_cmodel on refactor
 */
function islandora_object_has_fraction($object){
  $cmodel_id = $object->models[0];
  $query = "
    PREFIX fedora-model: <info:fedora/fedora-system:def/model#>
    SELECT ?datarel
    FROM <#ri>
    WHERE
    {
      {<info:fedora/islandora:fraction_cmodel> ?datarel <info:fedora/$cmodel_id>} .
    }
  ";

  $tuque = new IslandoraTuque();
  $result = $tuque->repository->ri->sparqlQuery($query, 'unlimited');

  if (sizeof($result) > 0)
    return TRUE;
  else
    return FALSE;
}

function islandora_lab_object_fraction_forms($form_id, $args){
  /**
   * @author Nolan Phillips ncphillips@upei.ca
   *
   * @param $form_id
   * @param $args
   * @return $forms
   *
   * Implements hook_forms($form_id, $args)
   *
   * This function is used to associate a new Form ID with an existing form constructor.
   */
  $forms = array();
  switch($form_id){
    /**
     * ## Related Assays Form
     * __Form ID:__ `related_fraction_form`
     *
     * __Form Base ID:__ `related_islandora_objects_form`
     *
     * Creates a `related_islandora_objects_form` with the `$cmodel` and `$relationships`
     * arguments set as:
     *
     *      $cmodels = array('islandora:fraction_cmodel');
     *      $relationships = array(FEDORA_RELS_EXT_URI => array('isPartOf'),);
     */
    case 'related_fraction_form':
      $cmodels = array('islandora:fraction_cmodel');
      $relationships = array(FEDORA_RELS_EXT_URI => array('isPartOf', 'isMemberOf',),);

      $args[] = $cmodels;
      $args[] = $relationships;

      $forms['related_fraction_form'] = array(
        'callback' => 'related_islandora_objects_form',
        'callback arguments' => $args,
      );
      break;
  }
  return $forms;
}


/**
 * This alters the base form to suit fraction data. Unfortunately I found that the fraction
 * data needed to be displayed too complexly for a form to be useful, so this really strips
 * out most of the form functionality.
 *
 * @param $form
 * @param $form_state
 */
function islandora_lab_object_fraction_form_related_fraction_form_alter(&$form, &$form_state){


  $fractions = $form_state['related_objects'];

  $form['selected'] = array();
  $form['submit'] = array();

  $form['table'] = array(
    "#type" => "hidden",
    "#prefix"=> theme('islandora_lab_object_fraction_table', array('islandora_objects' => $fractions))
  );


}

/**
 * Implements hook_islandora_required_objects()
 * 
 * @param $connection
 * An IslandoraTuque object which connects to the Fedora Repository to be altered.
 * 
 * @return array
 * An array containing the Fedora Objects created in this hook. 
 */
function islandora_lab_object_fraction_islandora_required_objects(IslandoraTuque $connection) {
  module_load_include('inc', 'islandora_bioinformatics_base', 'base_functions');


  $module_path = drupal_get_path('module', 'islandora_lab_object_fraction');
  $fraction_cm = $connection->repository->constructObject('islandora:fraction_cmodel');
  $fraction_cm->owner = 'fedoraAdmin';
  $fraction_cm->label = 'Fraction Content Model';
  $fraction_cm->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $fraction_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_lab_object_fraction_ds_composite_model.xml", FALSE);
  $fraction_cm->ingestDatastream($datastream);
  // Create relationship with LabObject
  $fraction_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  // Remove word _specimen and just have datarel
  $fraction_cm->relationships->add("", 'datarel_specimen', 'islandora:specimen_cmodel');

  // Fraction collection
  $fraction_collection = $connection->repository->constructObject('islandora:fraction_collection');
  $fraction_collection->owner = 'fedoraAdmin';
  $fraction_collection->label = 'Fraction Collection';
  $fraction_collection->models = 'islandora:collectionCModel';
  $fraction_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:lab_object_collection');
  $datastream = $fraction_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policies/islandora_lab_object_fraction_collection_policy.xml", FALSE);
  $fraction_collection->ingestDatastream($datastream);

  $fraction_cm->relationships->add(FEDORA_RELS_EXT_URI, 'datarel_isPartOf', 'islandora:specimen_cmodel');
    
  return array(
    'islandora_lab_object_fraction' => array(
      'title' => 'Fraction',
      'objects' => array(
          $fraction_cm,
          $fraction_collection,
      ),
    ),
  );
}

/**
 * @return array
 * An array with a form name as a key, and a path to the form as a value.
 */
function islandora_lab_object_fraction_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_fraction');
  $forms = array(
    'Fraction Form' => array(
      'form_file' => "$module_path/xml/forms/islandora_lab_object_fraction_form.xml",
    ),
    'Compound Form' => array(
      'form_file' => "$module_path/xml/forms/islandora_lab_object_fraction_compound_form.xml",
    ),
  );
  return $forms;
}

/**
 * @return array
 * returns default form associations
 */
function islandora_lab_object_fraction_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_fraction');
  $form_assoc = array(
    'islandora_lab_object_fraction_form' => array(
      'content_model' => "islandora:fraction_cmodel",
      'form_name' => 'Fraction Form',
      'dsid' => 'fraction',
      'transform' => '',
      'template' => FALSE,
      'title_field' => array('id'),
    ),
    'islandora_lab_object_fraction_compound_form' => array(
      'content_model' => "islandora:fraction_cmodel",
      'form_name' => 'Compound Form',
      'dsid' => 'fraction',
      'transform' => '',
      'template' => FALSE,
      'title_field' => array('id'),
    ),
  );
  return $form_assoc;
}


/**
 * Defines a theme for viewing a fraction as well as a theme for viewing a table
 * of fractions
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function islandora_lab_object_fraction_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_lab_object_fraction' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/fraction-theme',
      'pattern' => 'islandora_lab_object_fraction__',
      'variables' => array('islandora_object' => NULL),
    ),
    'islandora_lab_object_fraction_table' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/fraction-table-theme',
      'pattern' => 'islandora_lab_object_fraction_table__',
      'variables' => array(
          'islandora_objects' => NULL
      ),
    ),
  );
}

/**
 * @param $object
 * @param $page_number
 * @param $page_size
 * @return array
 */
function islandora_lab_object_fraction_islandora_fraction_cmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_lab_object_fraction', array('islandora_object' => $object));

  return array('islandora_lab_object_fraction' => $output);
}

/**
 * @param array $configuration
 * @return array
 */
function islandora_lab_object_fraction_islandora_fraction_cmodel_islandora_ingest_steps(array $configuration) {

  return array(
    'islandora_lab_object_fraction_specimen_form' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_lab_object_fraction_specimen_form',
      'module' => 'islandora_lab_object_fraction',
      'file' => 'includes/fraction_relate.form.inc'
    )
  );
}


/**
 * @author Brent Mitton
 * @param $string
 * Takes in part of a string that is currently being typed into a textbox
 * and then does a mysql LIKE query. For autocompletion on fraction forms
 */
function _assay_autocomplete($string){
  $matches = array();

   $or = db_or()
       ->condition('abbreviation', '%' . db_like($string) . '%', 'LIKE')
       ->condition('name', '%' . db_like($string) . '%', 'LIKE');

  $result = db_select('labobject_assay_assay', 'a')
      ->fields('a', array('abbreviation', 'name'))
      ->condition($or)
      ->execute();
  // save the query to matches
  foreach ($result as $row) {
    $matches[$row->name] = check_plain($row->abbreviation) . " - " . check_plain($row->name) ;
  }

  drupal_json_output($matches);
}

/**
 * Takes in an fraction object and returns an array.
 * @param $fraction_object
 *  An islandora fraction object
 * @return array
 *  A simple array containing the fraction information
 */
function fraction_object_to_array($fraction_object){

  $assays = array();
  // query the assays and store them
  $result = db_select('labobject_assay_assay', 'a')
      ->fields('a', array('abbreviation', 'name'))
      ->execute();

  foreach($result as $row){
    $assays[$row->abbreviation] = $row->name;
  }


  $ns = "http://www.upeikerrlab.ca";
  $fraction_array = array();

  $fraction_xml = new SimpleXMLElement($fraction_object["fraction"]->content);

  $i = 0;
  foreach($fraction_xml->children($ns) as $part){

    switch ((string) $part->getName()){
      case "type":
        $fraction_array["type"] = ((string)$part) ? (string)$part:"";
        break;
      case "labid":
        $fraction_array["labid"] = ((string)$part) ? (string)$part:"";
        break;
      case "weight":
        $fraction_array["weight"] = ((string)$part) ? (string)$part:"";
        break;
      case "plate":
        $fraction_array["plate"] = ((string)$part) ? (string)$part:"";
        break;
      case "location":
        $fraction_array["location"] = ((string)$part) ? (string)$part:"";
        break;
      case "notes":
        $fraction_array["notes"] = ((string)$part) ? (string)$part:"";
        break;
      case "inhibitor":

        foreach ($assays as $key => $value) {
          if ((string) $part->name == $value){
            $fraction_array["fraction"][$key]["name"] = $value;
            $fraction_array["fraction"][$key]["result"] = ((string)$part->result) ? (string)$part->result:"";
            $fraction_array["fraction"][$key]["comment"] = ((string)$part->comment) ? (string)$part->comment:"";

          }
        }
        break;
    }
  }

  return $fraction_array;
}


/**
 * @author Quintin Dawson qdawson@upei.ca
 * This function should create a new assay object and create a relationship between it and the $parent object
 */

function islandora_lab_object_fraction_ingest(AbstractObject $parent) {
  $collection = islandora_object_load('islandora:fraction_collection');
  if($collection !== FALSE) {
    if (($configuration = islandora_lab_object_fraction_load_ingest_configuration($collection, $parent)) !== FALSE) {
      module_load_include('inc', 'islandora', 'includes/ingest.form');
      return drupal_get_form('islandora_ingest_form', $configuration);
    }
  }
  drupal_not_found();
}


function islandora_lab_object_fraction_load_ingest_configuration(AbstractObject $collection, AbstractObject $parent) {
  $is_collection_object = in_array('islandora:collectionCModel', $collection->models);
  $has_policy = isset($collection['COLLECTION_POLICY']);
  if (!$is_collection_object || !$has_policy) {
    return array();
  }

  $object = $collection->repository->constructObject('islandora');
  $object->label = 'New Object';

  $results = $object->relationships->get(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $collection->id);
  if (empty($results)) {
    $object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $collection->id);
  }

  $results = $object->relationships->get(FEDORA_RELS_EXT_URI, 'isPartOf', $parent->id);
  if (empty($results)) {
    $object->relationships->add(FEDORA_RELS_EXT_URI, 'isPartOf', $parent->id);
  }

  $policy = new CollectionPolicy($collection['COLLECTION_POLICY']->content);

  return array(
    'collection' => $collection,
    'models' => array('islandora:fraction_cmodel'), //array_keys($policy->getContentModels()),
    'objects' => array($object),
    'parent' => $collection->id,
  );
}
