<?php
/**
 * * Implements hook_islandora_required_objects()
 * */
function islandora_bioinformatics_fraction_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_fraction');
  $fraction_cm = $connection->repository->constructObject('bioinformatics:fraction_cm');
  $fraction_cm->owner = 'fedoraAdmin';
  $fraction_cm->label = 'Bioinformatics Fraction Content Model';
  $fraction_cm->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $fraction_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_bioinformatics_fraction_ds_composite_model.xml", FALSE);
  $fraction_cm->ingestDatastream($datastream);
  
  // Fraction collection
  $fraction_collection = $connection->repository->constructObject('islandora:fraction_collection');
  $fraction_collection->owner = 'fedoraAdmin';
  $fraction_collection->label = 'Fraction Collection';
  $fraction_collection->models = 'islandora:collectionCModel';
  $fraction_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  $datastream = $fraction_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policies/islandora_bioinformatics_fraction_collection_policy.xml", FALSE);
  $fraction_collection->ingestDatastream($datastream);
    
  return array(
    'islandora_bioinformatics_fraction' => array(
      'title' => 'Bioinformatics Fraction',
      'objects' => array(
          $fraction_cm,
          $fraction_collection,
      ),
    ),
  );
}

function islandora_bioinformatics_fraction_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_fraction');
  return array(
    'Fraction Form' => array(
      'form_file' => "$module_path/xml/forms/islandora_bioinformatics_fraction_form.xml",
    ),
  );
}

function islandora_bioinformatics_fraction_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_fraction');
  return array(
    'islandora_bioinformatics_fraction_form' => array(
      'fraction_cm' => 'bioinformatics:fraction',
      'form_name' => 'Fraction Form',
      'dsid' => 'EML',
      'title_field' => array('taxonomy', 'species'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_bioinformatics_fraction_transform.xsl",
      'template' => FALSE,
    ),
  );
}
