<?php
/**
 * @file
 * Islandora Bioinformatics Fraction Module
 * 
 * @author Nolan Phillips ncphillips@upei.ca
 * @author Brent Mitton bmitton@upei.ca
 * @author Natasha Squires nbsquires@upei.ca
 * @author Quintin Dawson qdawson@upei.ca
 */

function islandora_lab_object_assay_menu(){
  return array(
    'assay/assays' => array(
      'title' => "Autocomplete Assays",
      'page callback' => "_assay_autocomplete",
      'access arguments' => TRUE,
      'type' => MENU_CALLBACK,
    ),
    'islandora/object/%islandora_object/test_ingest_assay' => array(
        'title' => 'Ingest Assay',
        'page callback' => 'rel_lab_object_assay_ingest',
        'page arguments' => array(2),
        'access callback' => TRUE,
      )
  );
}

function islandora_lab_object_assay_forms($form_id, $args){
  /**
   * @author Nolan Phillips ncphillips@upei.ca
   *
   * @param $form_id
   * @param $args
   * @return $forms
   *
   * Implements hook_forms($form_id, $args)
   *
   * This function is used to associate a new Form ID with an existing form constructor.
   */
  $forms = array();
  switch($form_id){
    /**
     * ## Related Assays Form
     * __Form ID:__ `related_assay_form`
     *
     * __Form Base ID:__ `related_islandora_objects_form`
     *
     * Creates a `related_islandora_objects_form` with the `$cmodel` and `$relationships`
     * arguments set as:
     *
     *      $cmodels = array('islandora:assay_cmodel');
     *      $relationships = array(FEDORA_RELS_EXT_URI => array('isPartOf'),);
     */
    case 'related_assay_form':
      $cmodels = array('islandora:assay_cmodel');
      $relationships = array(FEDORA_RELS_EXT_URI => array('isPartOf', 'isMemberOf',),);

      $args[] = $cmodels;
      $args[] = $relationships;

      $forms['related_assay_form'] = array(
        'callback' => 'related_islandora_objects_form',
        'callback arguments' => $args,
      );
      break;
  }
  return $forms;
}




function islandora_lab_object_assay_access($object) {
  return TRUE;
}

/**
 * Implements hook_islandora_required_objects()
 * 
 * @param $connection
 * An IslandoraTuque object which connects to the Fedora Repository to be altered.
 * 
 * @return array
 * An array containing the Fedora Objects created in this hook. 
 */
function islandora_lab_object_assay_islandora_required_objects(IslandoraTuque $connection) {
  echo "hellllo"; die;
  module_load_include('inc', 'islandora_bioinformatics_base', 'base_functions');


  $module_path = drupal_get_path('module', 'islandora_lab_object_assay');
  $assay_cm = $connection->repository->constructObject('islandora:assay_cmodel');
  $assay_cm->owner = 'fedoraAdmin';
  $assay_cm->label = 'Fraction Content Model';
  $assay_cm->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $assay_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_lab_object_assay_ds_composite_model.xml", FALSE);
  $assay_cm->ingestDatastream($datastream);
  // Create relationship with LabObject
  $assay_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  // Remove word _specimen and just have datarel
  $assay_cm->relationships->add("", 'datarel_specimen', 'islandora:specimen_cmodel');

  // Fraction collection
  $assay_collection = $connection->repository->constructObject('islandora:assay_collection');
  $assay_collection->owner = 'fedoraAdmin';
  $assay_collection->label = 'Assay Collection';
  $assay_collection->models = 'islandora:collectionCModel';
  $assay_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  $datastream = $assay_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policies/islandora_lab_object_assay_collection_policy.xml", FALSE);
  $assay_collection->ingestDatastream($datastream);

  echo "HELLLLO";
  die;
  $specimen_cm = islandora_object_load("islandora:specimen_cmodel");
  add_hasPart($specimen_cm, "islandora:assay_cmodel");
  add_isPartOf($assay_cm, "islandora:specimen_cmodel");
    
  return array(
    'islandora_lab_object_assay' => array(
      'title' => 'Assay',
      'objects' => array(
          $assay_cm,
          $assay_collection,
      ),
    ),
  );
}

/**
 * @return array
 * An array with a form name as a key, and a path to the form as a value.
 */
function islandora_lab_object_assay_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_assay');
  $forms = array(
    'Assay Form' => array(
      'form_file' => "$module_path/xml/forms/islandora_lab_object_assay_form.xml",
    ),
    'Compound Form' => array(
      'form_file' => "$module_path/xml/forms/islandora_lab_object_assay_compound_form.xml",
    ),
  );
  return $forms;
}

/**
 * @return array
 * returns default form associations
 */
function islandora_lab_object_assay_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_lab_object_assay');
  $form_assoc = array(
    'islandora_lab_object_assay_form' => array(
      'content_model' => "islandora:assay_cmodel",
      'form_name' => 'Assay Form',
      'dsid' => 'fraction',
      'transform' => '',
      'template' => FALSE,
      'title_field' => array('id'),
    ),
    'islandora_lab_object_assay_compound_form' => array(
      'content_model' => "islandora:assay_cmodel",
      'form_name' => 'Compound Form',
      'dsid' => 'fraction',
      'transform' => '',
      'template' => FALSE,
      'title_field' => array('id'),
    ),
  );
  return $form_assoc;
}


/**
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function islandora_lab_object_assay_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_lab_object_assay' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/assay-theme',
      'pattern' => 'islandora_lab_object_assay__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * @param $object
 * @param $page_number
 * @param $page_size
 * @return array
 */
function islandora_lab_object_assay_islandora_assay_cmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_lab_object_assay', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * @param array $configuration
 * @return array
 */
function islandora_lab_object_assay_islandora_assay_cmodel_islandora_ingest_steps(array $configuration) {

  return array(
    'islandora_lab_object_assay_specimen_form' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_lab_object_assay_specimen_form',
      'module' => 'islandora_lab_object_assay',
      'file' => 'includes/assay_relate.form.inc'
    )
  );
}


/**
 * @author Brent Mitton
 * @param $string
 * Takes in part of a string that is currently being typed into a textbox
 * and then does a mysql LIKE query. For autocompletion on assay forms
 */
function _assay_autocomplete($string){
  $matches = array();

   $or = db_or()
       ->condition('abbreviation', '%' . db_like($string) . '%', 'LIKE')
       ->condition('name', '%' . db_like($string) . '%', 'LIKE');

  $result = db_select('labobject_assay_assay', 'a')
      ->fields('a', array('abbreviation', 'name'))
      ->condition($or)
      ->execute();
  // save the query to matches
  foreach ($result as $row) {
    $matches[$row->name] = check_plain($row->abbreviation) . " - " . check_plain($row->name) ;
  }

  drupal_json_output($matches);
}

/**
 * Takes in an assay object and returns an array.
 * @param $assay_object
 *  An islandora assay object
 * @return array
 *  A simple array containing the assay information
 */
function assay_object_to_array($assay_object){

  $ns = "http://www.upeikerrlabs.ca";
  $assay_array = array();

  $assay_xml = new SimpleXMLElement($assay_object["fraction"]->content);


  foreach($assay_xml->children($ns) as $part){

    echo $part->getName();
  }

  die;
}

/**
* @author Quintin Dawson qdawson@upei.ca
*/
function rel_lab_object_assay_ingest($object) {


}
