<?php
/**
 * @file
 * Islandora Bioinformatics Fraction Module
 * 
 * @author Nolan Phillips ncphillips@upei.ca
 * @author Brent Mitton bmitton@upei.ca
 * @author Natasha Squires nbsquires@upei.ca
 */

/**
 * @author Brent Mitton bmitton@upei.ca
 * @author Nolan Phillips ncphillips@upei.ca
 */
function islandora_bioinformatics_fraction_menu(){
  return array(
    /**
     * @author Brent Mitton bmitton@upei.ca
     * 
     * A URL which begins the ingestion process for a new Fraction to
     * be associated with this specimen.
     */
    'islandora/object/%specimen_object/add/fraction' => array(
      'title' => 'Add Fraction',
      'type' => MENU_CALLBACK,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_bioinformatics_fraction_specimen_form'),
      'access callback' => 'islandora_bioinformatics_fraction_access',
      'access arguments' => array(2),
      'file' => 'includes/fraction_relate.form.inc'
    ),
    
    /**
     * @author Nolan Phillips ncphillips@upei.ca
     * 
     * Creates a tab alongside the Manage and View tabs which links to a page
     * listing the fractions derived from this specimen.
     */ 
    'islandora/object/%specimen_object/fractions' => array(
      'title' => 'Fractions',
      'type' => MENU_LOCAL_TASK,
      'description' => 'A list of fractions derived from this specimen.',
      'page callback' => 'specimen_fractions',
      'page arguments' => array(2),
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
      'file' => 'includes/manage_specimen.inc'
      )
  );
}


function islandora_bioinformatics_fraction_access($object){
  return true;
}


/**
 * Implements hook_islandora_required_objects()
 * 
 * @param $connection
 * An IslandoraTuque object which connects to the Fedora Repository to be altered.
 * 
 * @return array
 * An array containing the Fedora Objects created in this hook. 
 */
function islandora_bioinformatics_fraction_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_fraction');
  $fraction_cm = $connection->repository->constructObject('islandora:fraction_cmodel');
  $fraction_cm->owner = 'fedoraAdmin';
  $fraction_cm->label = 'Fraction Content Model';
  $fraction_cm->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $fraction_cm->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/content_models/islandora_bioinformatics_fraction_ds_composite_model.xml", FALSE);
  $fraction_cm->ingestDatastream($datastream);
  // Create relationship with LabObject
  $fraction_cm->relationships->add(FEDORA_MODEL_URI, 'hasModel', 'islandora:lab_object_cmodel');
  
  // Fraction collection
  $fraction_collection = $connection->repository->constructObject('islandora:fraction_collection');
  $fraction_collection->owner = 'fedoraAdmin';
  $fraction_collection->label = 'Fraction Collection';
  $fraction_collection->models = 'islandora:collectionCModel';
  $fraction_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  $datastream = $fraction_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/collection_policies/islandora_bioinformatics_fraction_collection_policy.xml", FALSE);
  $fraction_collection->ingestDatastream($datastream);
    
  return array(
    'islandora_bioinformatics_fraction' => array(
      'title' => 'Fraction',
      'objects' => array(
          $fraction_cm,
          $fraction_collection,
      ),
    ),
  );
}

/**
 * @return array
 * An array with a form name as a key, and a path to the form as a value.
 */
function islandora_bioinformatics_fraction_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_fraction');
  return array(
    'Fraction Form' => array(
      'form_file' => "$module_path/xml/forms/islandora_bioinformatics_fraction_form.xml",
    ),
  );
}

function islandora_bioinformatics_fraction_islandora_xml_form_builder_form_associations() {
  $module_path = drupal_get_path('module', 'islandora_bioinformatics_fraction');
  return array(
    'islandora_bioinformatics_fraction_form' => array(
      'fraction_cm' => 'islandora:fraction_cmodel',
      'form_name' => 'Fraction Form',
      'dsid' => 'EML',
      'title_field' => array('taxonomy', 'species'),
      'transform' => '',
      //'self_transform' => "$module_path/xml/islandora_bioinformatics_fraction_transform.xsl",
      'template' => FALSE,
    ),
  );
}




function islandora_bioinformatics_fraction_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_bioinformatics_fraction' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/fraction-theme',
      'pattern' => 'islandora_bioinformatics_fraction__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}


function islandora_bioinformatics_fraction_islandora_fraction_cmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_bioinformatics_fraction', array('islandora_object' => $object));
  return array('' => $output);
}


