<?php
/**
 * @file manage_fraction.inc
 */
 
 
 /**
  * @TODO
  * Find and list all fraction objects that were derived from
  * passed in Specimen object. This page should also have a link
  * to the 'islandora/objects/%specimen_object/add/fraction' URL
  * described in islandora_bioinformatics_fraction_menu().
  */
 function specimen_fractions(AbstractObject $specimen) {
   return "INCOMPLETE
 }
